function [X,Y]=findOrnsteinRec(x,y,x_val,y_val,eps,a,l,s2)
    if (abs(y-x)<eps) 
        X=[];
        Y=[];
        return
    end
    %a = rand(1);
    new_val = generateNormalRandomValue(...
        (exp(-l*a*(y-x))*(1-exp(-2*l*(1-a)*(y-x)))*x_val + ...
            exp(-l*(1-a)*(y-x))*(1-exp(-2*l*a*(y-x)))*y_val)/...
                (1-exp(-2*l*(y-x))),...
         s2*(1 - exp(-2*l*a*(y-x))-exp(-2*l*(1-a)*(y-x))+exp(-2*l*(y-x)))/...
               (1-exp(-2*l*(y-x)))... 
        ,rand(1),rand(1));
    %new_val = generateNormalRandomValueVonNeumanTrue((1-a)*x_val+a*y_val,...
    %    a*(1-a)*(y-x));
    [Xless,Yless] = findOrnsteinRec(x,x+(y-x)*a,x_val,new_val,eps,a,l,s2);
    [Xmore,Ymore] = findOrnsteinRec(x+(y-x)*a,y,new_val,y_val,eps,a,l,s2);
    Y = [Yless,...
         new_val,...
         Ymore];
    X = [Xless, x+(y-x)*a , Xmore];
    
